@startuml
'https://plantuml.com/class-diagram

' Classes
class Event{
Title
Description
Date
Time
Duration
Capacity
Location
Instructor
Price
Category
Image
Status
Create at
Updated at
Deleted at
}

class User{
Name
Email
Password
Phone
Role
}

' Relations
User "Many " -- "Many " Event: " Has"

hide methods
@enduml