### User login
POST http://localhost:7007/api/auth/login

{
"email":"hans@mail.com",
"password":"password"
}

### Register new user
POST http://localhost:7007/api/auth/register

{
"name": "Lasse",
"email": "l@lahy.dk",
"password": "1234qwer",
"phone": 53702510
}

### Logout
POST http://localhost:7007/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsQGxhaHkuZGsiLCJwaG9uZSI6NTM3MDI1MTAsInJvbGVzIjoic3R1ZGVudCIsImlzcyI6IlRlYW1MQUhZIiwibmFtZSI6InRlc3QiLCJpZCI6MTUwLCJleHAiOjE3MTIyMjU4OTUsImVtYWlsIjoibEBsYWh5LmRrIn0.ndBwIqx1timKW43OOtZuBivN1bfaNQ2CLFIz8alqqvE

### Update a user
PUT http://localhost:7007/api/users/873
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYW5zQG1haWwuY29tIiwicGhvbmUiOjEyMzQ1Njc4LCJyb2xlcyI6InN0dWRlbnQsYWRtaW4iLCJpc3MiOiJUZWFtTEFIWSIsIm5hbWUiOiJIYW5zIiwiaWQiOjg3MywiZXhwIjoxNzEyNTYzMDEyLCJlbWFpbCI6ImhhbnNAbWFpbC5jb20ifQ.2k1J0Lw-9O1_Q6LgeY_WOGdqXEIri2qwQYxTX_LTdsc

{
"name": "lasse"
}