### User login
POST http://localhost:7007/api/auth/login

{
"email":"l@lahy.dk",
"password":"1234qwer"
}

### Register new user
POST http://localhost:7007/api/auth/register

{
"name": "Lasse",
"email": "l@lahy.dk",
"password": "1234qwer",
"phone": 53702510
}