### Get all user.
GET http://localhost:7007/api/users

### Get a single user.
GET http://localhost:7007/api/users/3

### Create a new user
POST http://localhost:7007/api/users

{
"name": "Lasse",
"email": "lasse@lasse.dk",
"password" : "1234qwer",
"phone": 53702510
}

### Update a user
PUT http://localhost:7007/api/users/3

{
"name": "Emil"
}

### Delete a user
DELETE http://localhost:7007/api/users/1
